module.exports = { created_at: 'Sat Sep 12 23:09:06 +0000 2015',
    id: 642837368307875800,
    id_str: '642837368307875840',
    text: 'Apple iMac G4 20" 1.25GHz (2003) 1.25GB *Rare* #TFB http://t.co/pLjs9IPbK4 http://t.co/9S6Hckzg2S',
        source: '<a href="http://ifttt.com" rel="nofollow">IFTTT</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
{ id: 3297983688,
    id_str: '3297983688',
    name: 'peg papas',
    screen_name: 'pegcjl7889',
    location: 'USA',
    url: null,
    description: null,
    protected: false,
    verified: false,
    followers_count: 3,
    friends_count: 0,
    listed_count: 2,
    favourites_count: 0,
    statuses_count: 2580,
    created_at: 'Mon Jul 27 15:58:29 +0000 2015',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png'
    ,
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
        profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/625849870461472768/PDix4cV8_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/625849870461472768/PDix4cV8_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/3297983688/1438049194',
    default_profile: true,
        default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null },
geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities:
{ hashtags: [ [Object] ],
    trends: [],
    urls: [ [Object] ],
    user_mentions: [],
    symbols: [],
    media: [ [Object] ] },
extended_entities: { media: [ [Object] ] },
favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'lt',
    timestamp_ms: '1442099346602' };